---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/widgets


- search:
    provider: duckduckgo
    target: _blank
- weatherapi:
    label: Vremea # optional
    units: metric # or imperial
    latitude: 45.80000000
    longitude: 24.15000000
    apiKey: "{{HOMEPAGE_VAR_WEATHER_KEY}}"
    cache: 5 # Time in minutes to cache API responses, to stay within limits
- stocks:
    provider: finnhub
    color: true # optional, defaults to true
    cache: 1 # optional, default caches results for 1 minute
    watchlist:
      - TSLA
      - INTC
      - NVDA
      - AMD
      - MMAT
      - MSFT

